[tool.towncrier]
# Read https://github.com/ethereum/py-evm/newsfragments/README.md for instructions
package = "eth"
filename = "docs/release_notes.rst"
directory = "newsfragments"
underlines = ["-", "~", "^"]
issue_format = "`#{issue} <https://github.com/ethereum/py-evm/issues/{issue}>`__"
